[build]
  publish = "."



[[redirects]]
  from = "/exp 3.1"
  to = "/exp 3.1/exp3.1.html"
  status = 200

[[redirects]]
  from = "exp 3.2"
  to = "/exp 3.2/exp3.2.html"
  status = 200

[[redirects]]
  from = "/exp 3.3"
  to = "/exp 3.3/exp3.3.html"
  status = 200